In [1]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [4]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (1).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
#Declare label as last column in the source file
label=data['Purchased']
label

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [6]:
#Declaring X as all columns excluding last
X=data[['Age','EstimatedSalary']]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [7]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,label,test_size=0.3,random_state=50)
X_train, X_test, y_train, y_test

(     Age  EstimatedSalary
 114   42            80000
 25    47            20000
 99    28            37000
 90    22            81000
 271   59            76000
 ..   ...              ...
 132   30            87000
 289   37            78000
 109   38            80000
 395   46            41000
 176   35            47000
 
 [280 rows x 2 columns],      Age  EstimatedSalary
 146   27            96000
 332   42            65000
 67    23            82000
 362   47            50000
 102   32            86000
 ..   ...              ...
 355   60            34000
 244   41            72000
 217   40            78000
 168   29           148000
 74    32            18000
 
 [120 rows x 2 columns], 114    0
 25     1
 99     0
 90     0
 271    1
       ..
 132    0
 289    1
 109    0
 395    1
 176    0
 Name: Purchased, Length: 280, dtype: int64, 146    1
 332    0
 67     0
 362    1
 102    0
       ..
 355    1
 244    0
 217    0
 168    1
 74     0
 Name: Purchased, Length: 120, dtype

In [8]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [10]:
entries = len(X_train[:,0])
entries

280

In [11]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [12]:
# Sigmoid function
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [13]:

def predict(inputs,w):
    z=np.dot(inputs,w)
    return sigmoid(z)

In [14]:
def loss_func(features,labels,w):
    observations = len(labels)
    predictions = predict(features, w)
    class1_cost = -labels*np.log(predictions)
    class2_cost = (1-labels)*np.log(1-predictions)
    cost = class1_cost - class2_cost
    cost = cost.sum() / observations
    return cost        

In [16]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

def update_weights(features, labels, weights, lr):    
    
    N = len(features)    
    predictions = predict(features, weights)    
    gradient = np.dot(features.T,  predictions - labels)    
    gradient /= N    
    gradient *= lr    
    weights -= gradient

    return weights

In [17]:
#Repeating the process 3000 times
cost_history = []
for i in range(3000):
    w = update_weights(X, label, w, alpha)

    #Calculate error for auditing purposes
    cost = loss_func(X, label, w)
    cost_history.append(cost)

    # Log Progress
    if i % 1000 == 0:
        print("iter: "+ str(i) + " cost: "+str(cost))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


iter: 0 cost: inf
iter: 1000 cost: inf
iter: 2000 cost: inf


In [18]:
#Print weight
w

array([ -19.43575, 1407.375  ])

In [19]:
#print bias
b

0.2

In [20]:
#predicting the label
predicted_labels=predict(X_test,w)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [21]:
#print actual and predicted values in a table
predicted_labels,label


(array([1.00000000e+000, 1.62433749e-081, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 1.78668240e-278, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 3.48274532e-223, 0.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.07761793e-301,
        0.00000000e+000, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 6.60095739e-143, 1.00000000e+000,
        2.10057971e-246, 0.00000000e+000, 0.00000000e+000, 6.50551737e-009,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.64

In [22]:
# Calculating accuracy of prediction
diff = predicted_labels - y_test
acc=1.0 - (float(np.count_nonzero(diff)) / len(diff))
acc

0.42500000000000004

#Using sklearn LogisticRegression model

In [23]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR=LR.fit(X_train,y_train)


#predicting the test label with LR. Predict always takes X as input
y_pred=LR.predict(X_test)
y_pred


array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

**Exercise:**

Try logistic regression on BuyComputer dataset and set Random state=Your_RollNumber (last 3 digit of ID, incase if you don't have ID)